### ISSUE TITLE
Right clicking resourceful crop plant with hoe crashes server

### ISSUE THREAD

**Issue by joral** [TehNut-Mods/ResourcefulCrops#49]
Reported on the nutsandbolts github project, and confirmed:

Version 1.7.10-1.0.0-26

Time: 8/2/17 10:28 AM
Description: Exception in server tick loop
 
java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
    at tehnut.resourceful.crops.util.ChatUtil.sendNoSpamMessages(ChatUtil.java:68)
    at tehnut.resourceful.crops.util.ChatUtil.sendNoSpamClient(ChatUtil.java:174)
    at tehnut.resourceful.crops.util.ChatUtil.sendNoSpamClient(ChatUtil.java:165)
    at tehnut.resourceful.crops.block.BlockRCrop.doReqInfo(BlockRCrop.java:283)
    at tehnut.resourceful.crops.block.BlockRCrop.func_149727_a(BlockRCrop.java:149)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 16 more

Full crash report
https://pastebin.com/iXD3srCs

**Comment by TehNut** [comment]
Stop using ancient versions of Minecraft.

**Comment by Saereth** [comment]
hey @TehNut mind if I fix this and include a custom build for the pack? obviously you arent expected to support 1.7 but I wouldnt mind since some people are still enjoying that pack.

**Comment by TehNut** [comment]
Sure

**Comment by m0nkm0nk** [comment]
@Saereth Any chance you would share your custom build? Pls :D
