### ISSUE TITLE
Game crashes when viewing items in creative inventory in 1.12.1. No other mods installed

### ISSUE THREAD

**Issue by Lothrazar** [TehNut-Mods/ResourcefulCrops#51]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 9/8/17 7:41 PM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at tehnut.resourceful.crops.proxy.ClientProxy.lambda$init$1(ClientProxy.java:61)
	at tehnut.resourceful.crops.proxy.ClientProxy$$Lambda$108/714100928.func_186726_a(Unknown Source)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:147)
	at net.minecraft.client.renderer.RenderItem.func_191970_a(RenderItem.java:211)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:125)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:144)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:303)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:342)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:644)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at tehnut.resourceful.crops.proxy.ClientProxy.lambda$init$1(ClientProxy.java:61)
	at tehnut.resourceful.crops.proxy.ClientProxy$$Lambda$108/714100928.func_186726_a(Unknown Source)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:147)
	at net.minecraft.client.renderer.RenderItem.func_191970_a(RenderItem.java:211)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:125)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:144)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:303)

-- Item being rendered --
Details:
	Item Type: tehnut.resourceful.crops.item.ItemResourcefulSeed@50cdaf32
	Item Aux: 0
	Item NBT: {seed:"resourcefulcrops:inky"}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:342)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:644)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (394, 176). Absolute: (788, 692)
	Screen size: Scaled: (960, 523). Absolute: (1920, 1045). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Lothrazar'/2074, l='MpServer', x=59.50, y=64.00, z=257.50]]
	Chunk stats: MultiplayerChunkCache: 506, 506
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (60,64,256), Chunk: (at 12,4,0 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 111 game time, 111 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 80 total; [EntitySheep['Sheep'/67, l='MpServer', x=-6.50, y=72.00, z=198.50], EntitySheep['Sheep'/68, l='MpServer', x=-2.50, y=70.00, z=199.50], EntitySheep['Sheep'/69, l='MpServer', x=-5.50, y=72.00, z=195.50], EntitySheep['Sheep'/70, l='MpServer', x=-2.51, y=71.00, z=198.06], EntitySheep['Sheep'/71, l='MpServer', x=-6.50, y=70.00, z=325.50], EntitySheep['Sheep'/72, l='MpServer', x=-2.50, y=67.00, z=323.50], EntitySheep['Sheep'/73, l='MpServer', x=-2.94, y=67.00, z=325.04], EntitySheep['Sheep'/74, l='MpServer', x=-6.50, y=70.00, z=326.50], EntitySheep['Sheep'/87, l='MpServer', x=24.59, y=65.00, z=213.60], EntitySheep['Sheep'/88, l='MpServer', x=27.50, y=65.00, z=210.50], EntitySheep['Sheep'/89, l='MpServer', x=22.58, y=65.00, z=217.14], EntitySheep['Sheep'/90, l='MpServer', x=19.75, y=65.00, z=218.41], EntitySheep['Sheep'/91, l='MpServer', x=30.39, y=64.00, z=242.55], EntitySheep['Sheep'/92, l='MpServer', x=23.77, y=64.00, z=237.52], EntitySheep['Sheep'/93, l='MpServer', x=31.43, y=64.00, z=242.13], EntitySheep['Sheep'/94, l='MpServer', x=33.18, y=64.00, z=245.48], EntitySheep['Sheep'/102, l='MpServer', x=46.50, y=65.00, z=309.50], EntitySheep['Sheep'/103, l='MpServer', x=48.50, y=66.00, z=307.50], EntitySheep['Sheep'/104, l='MpServer', x=48.50, y=65.00, z=304.50], EntitySheep['Sheep'/105, l='MpServer', x=46.50, y=65.00, z=306.50], EntityCreeper['Creeper'/4201, l='MpServer', x=17.50, y=34.00, z=326.50], EntityPig['Pig'/106, l='MpServer', x=42.50, y=65.00, z=309.50], EntityPig['Pig'/107, l='MpServer', x=42.50, y=64.00, z=307.50], EntityPig['Pig'/108, l='MpServer', x=44.50, y=65.00, z=308.50], EntityPig['Pig'/109, l='MpServer', x=48.50, y=66.00, z=309.50], EntitySheep['Sheep'/123, l='MpServer', x=102.50, y=64.00, z=178.50], EntitySheep['Sheep'/124, l='MpServer', x=102.50, y=63.83, z=186.52], EntitySheep['Sheep'/125, l='MpServer', x=102.50, y=64.00, z=185.64], EntitySheep['Sheep'/126, l='MpServer', x=97.40, y=64.00, z=185.20], EntityVillager['Villager'/127, l='MpServer', x=92.50, y=63.94, z=184.55], EntityRabbit['Rabbit'/128, l='MpServer', x=95.50, y=63.00, z=269.50], EntityRabbit['Rabbit'/129, l='MpServer', x=97.50, y=63.00, z=270.50], EntityRabbit['Rabbit'/130, l='MpServer', x=96.50, y=63.00, z=269.50], EntityCreeper['Creeper'/4229, l='MpServer', x=85.50, y=19.00, z=308.50], EntitySpider['Spider'/4277, l='MpServer', x=24.50, y=24.00, z=179.50], EntityBat['Bat'/4367, l='MpServer', x=77.25, y=38.99, z=225.25], EntityBat['Bat'/4368, l='MpServer', x=77.26, y=38.05, z=226.57], EntityBat['Bat'/4381, l='MpServer', x=108.23, y=52.06, z=319.67], EntityCreeper['Creeper'/4462, l='MpServer', x=51.50, y=23.00, z=337.50], EntitySkeleton['Skeleton'/4477, l='MpServer', x=96.50, y=30.00, z=221.50], EntitySkeleton['Skeleton'/4511, l='MpServer', x=111.50, y=55.00, z=323.50], EntitySkeleton['Skeleton'/4512, l='MpServer', x=111.50, y=55.00, z=325.67], EntityZombie['Zombie'/4527, l='MpServer', x=54.50, y=22.00, z=323.50], EntityCreeper['Creeper'/4575, l='MpServer', x=45.50, y=51.00, z=327.50], EntityCreeper['Creeper'/4597, l='MpServer', x=121.14, y=44.00, z=210.70], EntitySkeleton['Skeleton'/4598, l='MpServer', x=124.50, y=44.00, z=213.50], EntityZombie['Zombie'/4611, l='MpServer', x=113.50, y=43.00, z=213.50], EntityZombie['Zombie'/4612, l='MpServer', x=112.50, y=43.00, z=213.50], EntityCreeper['Creeper'/4627, l='MpServer', x=94.50, y=41.00, z=216.50], EntitySkeleton['Skeleton'/4629, l='MpServer', x=93.50, y=41.00, z=216.50], EntitySkeleton['Skeleton'/4630, l='MpServer', x=31.50, y=33.00, z=237.50], EntitySkeleton['Skeleton'/4655, l='MpServer', x=88.50, y=50.00, z=210.50], EntitySkeleton['Skeleton'/4782, l='MpServer', x=98.71, y=57.52, z=327.66], EntityZombie['Zombie'/4818, l='MpServer', x=49.50, y=28.00, z=259.50], EntitySkeleton['Skeleton'/4891, l='MpServer', x=89.50, y=51.00, z=218.50], EntityCreeper['Creeper'/4892, l='MpServer', x=90.50, y=51.00, z=218.50], EntitySkeleton['Skeleton'/4929, l='MpServer', x=125.50, y=25.00, z=239.50], EntitySkeleton['Skeleton'/4930, l='MpServer', x=127.50, y=25.00, z=238.50], EntityCreeper['Creeper'/4946, l='MpServer', x=-19.50, y=24.00, z=202.50], EntitySkeleton['Skeleton'/4983, l='MpServer', x=18.50, y=37.00, z=318.50], EntitySkeleton['Skeleton'/5009, l='MpServer', x=41.50, y=38.00, z=233.50], EntityZombie['Zombie'/5075, l='MpServer', x=49.50, y=22.00, z=336.50], EntityCreeper['Creeper'/5103, l='MpServer', x=16.50, y=50.00, z=313.50], EntityCreeper['Creeper'/5157, l='MpServer', x=53.50, y=29.00, z=317.50], EntityCreeper['Creeper'/5158, l='MpServer', x=53.50, y=29.00, z=317.50], EntitySkeleton['Skeleton'/5270, l='MpServer', x=33.50, y=31.00, z=264.50], EntityZombie['Zombie'/5289, l='MpServer', x=-12.50, y=31.00, z=243.50], EntitySkeleton['Skeleton'/5382, l='MpServer', x=81.50, y=38.00, z=233.50], EntityBat['Bat'/5493, l='MpServer', x=53.65, y=38.68, z=258.58], EntityPlayerSP['Lothrazar'/2074, l='MpServer', x=59.50, y=64.00, z=257.50], EntitySquid['Squid'/2526, l='MpServer', x=89.01, y=60.76, z=195.95], EntitySquid['Squid'/2527, l='MpServer', x=84.34, y=58.15, z=193.25], EntitySquid['Squid'/2529, l='MpServer', x=90.60, y=59.58, z=198.81], EntitySquid['Squid'/2539, l='MpServer', x=81.69, y=59.51, z=199.56], EntitySquid['Squid'/2540, l='MpServer', x=73.05, y=58.24, z=313.00], EntitySquid['Squid'/2541, l='MpServer', x=80.87, y=58.66, z=317.41], EntitySquid['Squid'/2542, l='MpServer', x=75.55, y=59.68, z=308.15], EntitySquid['Squid'/2543, l='MpServer', x=77.08, y=58.93, z=308.83], EntitySkeleton['Skeleton'/2997, l='MpServer', x=-4.50, y=32.00, z=274.50], EntitySkeleton['Skeleton'/3003, l='MpServer', x=-3.50, y=32.00, z=273.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 236780144 bytes (225 MB) / 585302016 bytes (558 MB) up to 4277534720 bytes (4079 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.41 Powered by Forge 14.22.0.2474 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID               | Version       | Source                             | Signature                                |
	|:--------- |:---------------- |:------------- |:---------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft        | 1.12.1        | minecraft.jar                      | None                                     |
	| UCHIJAAAA | mcp              | 9.19          | minecraft.jar                      | None                                     |
	| UCHIJAAAA | FML              | 8.0.99.99     | forge-1.12.1-14.22.0.2474.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge            | 14.22.0.2474  | forge-1.12.1-14.22.0.2474.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | resourcefulcrops | 1.12-2.1.0-61 | ResourcefulCrops-1.12-2.1.0-61.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 381.65' Renderer: 'GeForce GT 730/PCIe/SSE2'
	Launched Version: forge-14.22.0.2474
	LWJGL: 2.9.4
	OpenGL: GeForce GT 730/PCIe/SSE2 GL version 4.5.0 NVIDIA 381.65, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz

**Comment by TehNut** [comment]
This is what I get for just marking it as working for 1.12.1 without trying ¯\\\_(ツ)_/¯

**Comment by TehNut** [comment]
Could you enable `debugLogging` in the config and check for messages matching `Generating color for seed {}` during startup?

**Comment by Lothrazar** [comment]
Yep for sure. I set   B:debugLogging=true  


This is the full "latest.log", i do not see any "Generating color for seed " related text

It does say " Finished loading 1 seeds in 18.29 ms"

https://pastebin.com/8rc3TFcs
